---
- name: Update packages first
  become: yes
  apt:
    update_cache: yes

- name: Install sudo
  become: yes
  package: name=sudo state=present

# Workaround from issue #492 on ansible-container
- name: Install libssl
  become: yes
  raw: apt-get install -y libssl-dev
  when: ansible_distribution == 'Ubuntu'

- name: Instalar paquetes
  become: yes
  package: name={{ item }} state=present
  with_items:
    - htop
    - git
    - vim-nox
    - speedometer
    - tree
    - silversearcher-ag

- name: Config VIM
  git:
    repo: "https://github.com/rubencabrera/vim.git"
    dest: "{{ ansible_env.HOME }}/vim"
    version: master
    force: yes

- name: Vundle for vim
  git:
    repo: "https://github.com/gmarik/vundle.git"
    dest: "{{ ansible_env.HOME }}/vim/.vim/Vundle.vim"
    version: master
    force: yes

- name: Set up vimrc
  file:
    src: "{{ ansible_env.HOME }}/vim/.vim/.vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: link

- name: Clear .vim default direcotry
  stat:
    path: "{{ ansible_env.HOME }}/.vim"
  register: sym

- name: Removing .vim default folder
  file:
    path: "{{ ansible_env.HOME }}/.vim"
    state: absent
  when: sym.stat.islnk is defined and not sym.stat.islnk

- name: Set up vim folder
  file:
    force: yes
    src: "{{ ansible_env.HOME }}/vim/.vim"
    dest: "{{ ansible_env.HOME }}/.vim"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: link
