---
- name: Update packages first
  become: yes
  apt:
    update_cache: yes
  when: '"personales" in group_names'

- name: Install sudo
  become: yes
  package: name=sudo state=present
  when: '"personales" in group_names'

- name: Instalar paquetes
  become: yes
  package: name={{ item }} state=present
  with_items:
    - htop
  when: '"personales" in group_names'

- name: Portátil personal
  import_tasks: portatil.yml
