---
- name: Rol del repo de epel para CentOS
  become: yes
  include_role:
    name: repo-epel
  when: ansible_distribution == 'CentOS'

- name: Update packages first
  become: yes
  apt:
    update_cache: yes

- name: Install sudo
  become: yes
  package: name=sudo state=present

# Workaround from issue #492 on ansible-container
- name: Install libssl
  become: yes
  raw: apt-get install -y libssl-dev
  when: ansible_distribution == 'Ubuntu'

- name: Add seafile repo
  apt_repository:
    repo: 'ppa:seafile/seafile-client'
    codename: "{{ 'xenial' if ansible_lsb.codename == 'sylvia' or ansible_lsb.codename == 'sonya' else ansible_lsb.codename }}"


- name: Instalar paquetes
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - htop
    - git
    - vim-nox
    - speedometer
    - tree
    - silversearcher-ag
    - psensor
    - python-pip
    - keepass2
    - python-setuptools
    - seafile-gui
    

#- name: Set home folder
  #set_fact:
    #ansible_home: ""

# Docker CE setup:
##################

- name : Asegurar que usamos la api nueva de docker
  become: True
  pip: 
    name: "{{ item }}"
    state: absent
  with_items:
    - docker-py

- name : Dependencias del módulo ansible_container
  become: True
  pip: 
    name: "{{ item }}"
  with_items:
    - docker

- name: HTTPS APT transport for Docker repository
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    keyserver: "{{ apt_key_url }}"
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    mode: '644'
    update_cache: yes
    state: present

- name: Install (or update) docker package
  apt:
    name: "{{ docker_pkg_name }}"
    state: "{{ 'latest' if update_docker_package else 'present' }}"
    update_cache: "{{ update_docker_package }}"
    cache_valid_time: "{{ docker_apt_cache_valid_time }}"

- name: Instalar docker.
  become: True
  apt: 
    pkg: docker-ce
    state: present

# End of Docker CE setup
########################

# These vim tasks can be avoided if using the installer in my own repo
- name: Config VIM
  git: 
    repo: "https://github.com/rubencabrera/vim.git"
    dest: "{{ ansible_env.HOME }}/vim"
    force: yes

# TODO: ejecutar instalar.py e interactuar con la contraseña necesaria.
#

 
