---
- name: Rol del repo de epel para CentOS
  become: yes
  include_role:
    name: repo-epel
  when: ansible_distribution == 'CentOS'

- name: Update packages first
  become: yes
  #become_method: su
  apt:
    update_cache: yes

- name: Install sudo
  become: yes
  #become_method: su
  package: name=sudo state=present

# Workaround from issue #492 on ansible-container
- name: Install libssl
  become: yes
  raw: apt-get install -y libssl-dev
  when: ansible_distribution == 'Ubuntu'

- name: Instalar paquetes
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - htop
    - git
    - vim-nox
    - speedometer
    - tree
    - silversearcher-ag

#- name: Set home folder
  #set_fact:
    #ansible_home: ""

- name: Config VIM
  git: 
    repo: "https://github.com/rubencabrera/vim.git"
    dest: "{{ ansible_env.HOME }}/vim"
    force: yes

- name: Vundle for vim
  git: 
    repo: "https://github.com/gmarik/vundle.git"
    dest: "{{ ansible_env.HOME }}/vim/.vim/Vundle.vim"
    force: yes

- name: Set up vimrc
  file:
    src: "{{ ansible_env.HOME }}/vim/.vim/.vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: link

- name: Clear .vim default direcotry
  stat:
    path: "{{ ansible_env.HOME }}/.vim"
  register: sym

- name: Removing .vim default folder
  file:
    path: "{{ ansible_env.HOME }}/.vim"
    state: absent
  when: sym.stat.islnk is defined and sym.stat.islnk == False

- name: Set up vim folder
  file:
    force: yes
    src: "{{ ansible_env.HOME }}/vim/.vim"
    dest: "{{ ansible_env.HOME }}/.vim"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: link
