---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
  - name: ubuntuBionic
    image: ubuntu:18.04
  - name: ubuntuXenial
    image: ubuntu:16.04
  - name: debianStretch
    image: debian:stretch
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
